### ISSUE TITLE
better tooling for handling Nanoseconds

### ISSUE THREAD

**Issue by murphsp1** [BTrDB/btrdb4-python#6]
In general, handling nanoseconds in Python is not terribly pleasant. It would make sense to create some tooling or helper classes around this issue. As time stamps in nanoseconds are incredibly large, it is easy to screw up the order of magnitude?

Do we use datetime? Time? Arrow? Pandas? 

Some possible helper functions are below.

```python
def ConvertDateTimeToEpoch_ns(dt):
    """
    converts the datetime object to epoch time in nanoseconds
    """
    
    return (int(dt.strftime('%s'))*1e6 + dt.microsecond)*1e3

def ConvertEpoch_nsToDateTime(ns):
    """
    converts the Epoch time in nanoseconds into a datetime object
    """
    
    return (datetime.fromtimestamp(ns/1e9).strftime('%c'))
```

It would be nice to be able to decrement by an "hour" or "minute" or "day"

**Comment by looselycoupled** [comment]
This was implemented in the v5 version of the bindings and can be found at https://github.com/BTrDB/btrdb4-python/blob/develop/btrdb/utils/timez.py

There will be a new issue that allows more options for `to_nanoseconds`
