### ISSUE TITLE
problems with parameter types

### ISSUE THREAD

**Issue by murphsp1** [BTrDB/btrdb4-python#7]
Variable types is a bit unforgiving in the library. 

## Nanoseconds
For example - nanoseconds must be in integers. We could simply cast nanosecond parameters as integers within the api methods instead of throwing errors. There could be a performance penalty for doing this.

## String encoding as Bytes
There are also some instances where the user has to take a string and turn it into a sequence of bytes in a particular character encoding. This can easily be done inside the API using either of the following to generate b'bytes':

```python
u'something'.encode('utf-8')
bytes(u'something', 'utf-8')
```

**Comment by looselycoupled** [comment]
A convenience method has been added for nanoseconds and the bytes/string issue has been resolved in the develop branch for the next release. Closing issue as stale and superseded by upcoming release.
