### ISSUE TITLE
Prepare and upload this project to Pypi for easier install

### ISSUE THREAD

**Issue by murphsp1** [BTrDB/btrdb4-python#9]
https://packaging.python.org/tutorials/distributing-packages/

**Comment by bbengfort** [comment]
Both @looselycoupled and I have access to PyPI and it has been uploaded. We'll continue to maintain the project there.

**Comment by looselycoupled** [comment]
@bbengfort can you verify my access when you get a chance?

**Comment by bbengfort** [comment]
@looselycoupled I have maintainer access not admin access so I can't, sorry - @immesys?

**Comment by looselycoupled** [comment]
@immesys has provided access and a current version is available through pip.  Closing issue.
